### ISSUE TITLE
Necessity of including web or webflux starters

### ISSUE THREAD

**Issue by oclay1st** [muhamadto/spring-native-aws-lambda#1]
Do I need to include spring-boot-starter-webflux or spring-cloud-starter-function-web to deploy a native build on AWS Lambda?
Is it mandatory?

Thanks for sharing!!

**Comment by oclay1st** [comment]
solved!!

**Comment by muhamadto** [comment]
@oclay1st I believe they are mandatory especially if you are using a reactive mode. Does this help?
