### ISSUE TITLE
create a leightweight even "spring boot less" deployment

### ISSUE THREAD

**Issue by cforce** [muhamadto/spring-native-aws-lambda#17]
Using API Gateway + AWS Lambda + Spring Boot is duplicating responsibilities. In the world before Serverless you would have used Spring Boot alone to handle HTTP requests and implement your business logic. Now the combination of API Gateway and AWS Lambda is replacing it. Even more than that, it enables you to have better scalability because of this separation of concerns from an operational aspect. This means you can put a big question mark on the idea of running Spring Boot inside AWS Lambda.
Also spring boot add a lot more byte sinto your package and later the image. So why use spring boot at all? It shall be possible to run the function without any http context by using aws native message communication
Deploymh behind a api AWS API Gateway  or even AWS Kinesis Stream shall allow us finally to get rid of as much as dependencies as possibe.

https://docs.spring.io/spring-cloud-function/docs/current/reference/html/aws.html#_custom_runtime
https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-samples/function-sample-aws-custom-bean/pom.xml

**Comment by cforce** [comment]
https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-samples/function-sample-aws/pom.xml

Using spring-boot-thin-layout and aws adapter

**Comment by muhamadto** [comment]
@cforce I'm not sure I understand what you need, but, it seems to me that you are not for for using spring boot for Cloud functions. Is this fair assessment?

**Comment by muhamadto** [comment]
Closing for lack of response
