### ISSUE TITLE
Request to add cloud formation template .

### ISSUE THREAD

**Issue by siddharthjain210** [muhamadto/spring-native-aws-lambda#5]
i have been trying the same steps. The lambda is also successfully created, but while testing the actual functions doesnt get invoked. 

`2022-01-05 17:26:11.442  INFO 9 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2022-01-05 17:26:11.443  INFO 9 --- [           main] com.graalvm.demo.DemoApplication         : Started DemoApplication in 0.777 seconds (JVM running for 1.062)
END RequestId: ee0b78ff-4521-4644-9feb-d8ef43434791
REPORT RequestId: ee0b78ff-4521-4644-9feb-d8ef43434791	Duration: 10010.46 ms	Billed Duration: 10000 ms	Memory Size: 512 MB	Max Memory Used: 89 MB	
2022-01-05T17:26:20.149Z ee0b78ff-4521-4644-9feb-d8ef43434791 Task timed out after 10.01 seconds
`

can you share the CFT or serverless template to test the lambda with an API GW Trigger.

**Comment by muhamadto** [comment]
What did you add as a handler?
