### ISSUE TITLE
docker build Error

### ISSUE THREAD

**Issue by go-ad** [muhamadto/spring-native-aws-lambda#7]
When i Do the 
```
docker build --no-cache \
--tag spring-native-aws-lambda:0.0.1-SNAPSHOT \
--file Dockerfile .
```
I  get Error,i want solve it .how to do .

Error: Image build request failed with exit status 137
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25:07 min
[INFO] Finished at: 2022-06-23T04:57:58Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.graalvm.nativeimage:native-image-maven-plugin:21.2.0:native-image (default) on project spring-native-aws-lambda: Execution of /app/graalvm-ce-java11-21.1.0/lib/svm/bin/native-image -cp /root/.m2/repository/org/springframework/experimental/spring-native/0.10.5/spring-native-0.10.5.jar:/root/.m2/repository/org/springframework/boot/spring-boot-starter-webflux/2.5.6/spring-boot-starter-webflux-2.5.6.jar:/root/.m2/repository/org/springframework/boot/spring-boot-starter/2.5.6/spring-boot-starter-2.5.6.jar:/root/.m2/repository/org/springframework/boot/spring-boot/2.5.6/spring-boot-2.5.6.jar:/root/.m2/repository/org/springframework/spring-context/5.3.12/spring-context-5.3.12.jar:/root/.m2/repository/org/springframework/spring-aop/5.3.12/spring-aop-5.3.12.jar:/root/.m2/repository/org/springframework/spring-expression/5.3.12/spring-expression-5.3.12.jar:/root/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.5.6/spring-boot-autoconfigure-2.5.6.jar:/root/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.5.6/spring-boot-starter-logging-2.5.6.jar:/root/.m2/repository/ch/qos/logback/logback-classic/1.2.6/logback-classic-1.2.6.jar:/root/.m2/repository/ch/qos/logback/logback-core/1.2.6/logback-core-1.2.6.jar:/root/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.14.1/log4j-to-slf4j-2.14.1.jar:/root/.m2/repository/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar:/root/.m2/repository/org/slf4j/jul-to-slf4j/1.7.32/jul-to-slf4j-1.7.32.jar:/root/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/root/.m2/repository/org/yaml/snakeyaml/1.28/snakeyaml-1.28.jar:/root/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.5.6/spring-boot-starter-json-2.5.6.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.5/jackson-databind-2.12.5.jar:/root/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.12.5/jackson-datatype-jdk8-2.12.5.jar:/root/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.5/jackson-datatype-jsr310-2.12.5.jar:/root/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.12.5/jackson-module-parameter-names-2.12.5.jar:/root/.m2/repository/org/springframework/boot/spring-boot-starter-reactor-netty/2.5.6/spring-boot-starter-reactor-netty-2.5.6.jar:/root/.m2/repository/io/projectreactor/netty/reactor-netty-http/1.0.12/reactor-netty-http-1.0.12.jar:/root/.m2/repository/io/netty/netty-codec-http/4.1.69.Final/netty-codec-http-4.1.69.Final.jar:/root/.m2/repository/io/netty/netty-common/4.1.69.Final/netty-common-4.1.69.Final.jar:/root/.m2/repository/io/netty/netty-buffer/4.1.69.Final/netty-buffer-4.1.69.Final.jar:/root/.m2/repository/io/netty/netty-transport/4.1.69.Final/netty-transport-4.1.69.Final.jar:/root/.m2/repository/io/netty/netty-codec/4.1.69.Final/netty-codec-4.1.69.Final.jar:/root/.m2/repository/io/netty/netty-handler/4.1.69.Final/netty-handler-4.1.69.Final.jar:/root/.m2/repository/io/netty/netty-codec-http2/4.1.69.Final/netty-codec-http2-4.1.69.Final.jar:/root/.m2/repository/io/netty/netty-resolver-dns/4.1.69.Final/netty-resolver-dns-4.1.69.Final.jar:/root/.m2/repository/io/netty/netty-resolver/4.1.69.Final/netty-resolver-4.1.69.Final.jar:/root/.m2/repository/io/netty/netty-codec-dns/4.1.69.Final/netty-codec-dns-4.1.69.Final.jar:/root/.m2/repository/io/netty/netty-resolver-dns-native-macos/4.1.69.Final/netty-resolver-dns-native-macos-4.1.69.Final-osx-x86_64.jar:/root/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.69.Final/netty-transport-native-unix-common-4.1.69.Final.jar:/root/.m2/repository/io/netty/netty-transport-native-epoll/4.1.69.Final/netty-transport-native-epoll-4.1.69.Final-linux-x86_64.jar:/root/.m2/repository/io/projectreactor/netty/reactor-netty-core/1.0.12/reactor-netty-core-1.0.12.jar:/root/.m2/repository/io/netty/netty-handler-proxy/4.1.69.Final/netty-handler-proxy-4.1.69.Final.jar:/root/.m2/repository/io/netty/netty-codec-socks/4.1.69.Final/netty-codec-socks-4.1.69.Final.jar:/root/.m2/repository/org/springframework/spring-web/5.3.12/spring-web-5.3.12.jar:/root/.m2/repository/org/springframework/spring-beans/5.3.12/spring-beans-5.3.12.jar:/root/.m2/repository/org/springframework/spring-webflux/5.3.12/spring-webflux-5.3.12.jar:/root/.m2/repository/io/projectreactor/reactor-core/3.4.11/reactor-core-3.4.11.jar:/root/.m2/repository/org/springframework/cloud/spring-cloud-function-web/3.1.4/spring-cloud-function-web-3.1.4.jar:/root/.m2/repository/org/springframework/cloud/spring-cloud-function-context/3.1.4/spring-cloud-function-context-3.1.4.jar:/root/.m2/repository/net/jodah/typetools/0.6.2/typetools-0.6.2.jar:/root/.m2/repository/org/springframework/cloud/spring-cloud-function-core/3.1.4/spring-cloud-function-core-3.1.4.jar:/root/.m2/repository/org/springframework/spring-messaging/5.3.12/spring-messaging-5.3.12.jar:/root/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar:/root/.m2/repository/org/springframework/cloud/spring-cloud-function-adapter-aws/3.1.4/spring-cloud-function-adapter-aws-3.1.4.jar:/root/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.12.5/jackson-datatype-joda-2.12.5.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.5/jackson-annotations-2.12.5.jar:/root/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.5/jackson-core-2.12.5.jar:/root/.m2/repository/org/springframework/boot/spring-boot-starter-validation/2.5.6/spring-boot-starter-validation-2.5.6.jar:/root/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.54/tomcat-embed-el-9.0.54.jar:/root/.m2/repository/org/hibernate/validator/hibernate-validator/6.2.0.Final/hibernate-validator-6.2.0.Final.jar:/root/.m2/repository/jakarta/validation/jakarta.validation-api/2.0.2/jakarta.validation-api-2.0.2.jar:/root/.m2/repository/org/jboss/logging/jboss-logging/3.4.2.Final/jboss-logging-3.4.2.Final.jar:/root/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar:/root/.m2/repository/com/amazonaws/aws-lambda-java-events/3.10.0/aws-lambda-java-events-3.10.0.jar:/root/.m2/repository/joda-time/joda-time/2.6/joda-time-2.6.jar:/root/.m2/repository/org/reactivestreams/reactive-streams/1.0.0/reactive-streams-1.0.0.jar:/root/.m2/repository/org/projectlombok/lombok/1.18.20/lombok-1.18.20.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/root/.m2/repository/org/springframework/spring-core/5.3.12/spring-core-5.3.12.jar:/root/.m2/repository/org/springframework/spring-jcl/5.3.12/spring-jcl-5.3.12.jar:/app/target/spring-native-aws-lambda-0.0.1-SNAPSHOT.jar --enable-url-protocols=http -H:+AddAllCharsets -H:Name=spring-native-aws-lambda returned non-zero result -> [Help 1]

**Comment by muhamadto** [comment]
You running out of memory or disk space — more likely the memory. 
https://codefresh.io/docs/docs/troubleshooting/common-issues/error-code-137/

**Comment by go-ad** [comment]
Thank you i have solved it
